version: 0.2
phases:
  install:
    commands:
      - npm install -g @angular/cli
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - ng build --configuration production --output-path dist
  post_build:
    commands:
      - aws s3 sync dist s3://nombre-de-tu-bucket --delete
artifacts:
  files:
    - '**/*'
  base-directory: dist
