name: Deploy Angular App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        cd FrontendAngular
        npm ci

    - name: Build Angular app
      run: |
        cd FrontendAngular
        npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install AWS CDK
      run: npm install -g aws-cdk

    - name: CDK Deploy
      run: |
        cd infrastructure
        npm ci
        cdk deploy --require-approval never
