name: Angular Tests and Coverage

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'master'
      - 'develop'
      - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests and Generate Coverage
      run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage

    - name: Check Coverage
      run: |
        # Install lcov if it's not already installed
        if ! command -v lcov &> /dev/null; then
          sudo apt-get install lcov
        fi

        # Check the coverage and fail if it's below 70%
        COVERAGE=$(lcov --capture --directory coverage --output-file coverage.info && lcov --summary coverage.info | grep -oP 'Lines\s+:\s+\K[0-9]+(?=%)')
        echo "Coverage: $COVERAGE%"
        if [ "$COVERAGE" -lt 70 ]; then
          echo "Coverage is below 70%. Failing the job."
          exit 1
        fi
